### PR TITLE
Remove  'integrity' attributes from resources (close #235)

### LINKED ISSUE #235: Remove `integrity` attributes from resources
See: http://www.w3.org/TR/SRI/

This attribute is used to avoid MITM attacks. Attribute contains SHA of the desired resource. Which doesn't work for us. This is widely used currently. And it brokes e.g. GitHub proxying. I suggest to remove this attribute entirely. It applies only to `<script>` and `<link>` elements.

### PR DESCRIPTION
**Pull request by churkin**
\cc @inikulin @LavrovArtem

### CODE REVIEW

**Comment by churkin** [comment]
FPR

File: src/processing/dom/index.js [hunk 1]
```diff
@@ -209,6 +216,13 @@ export default class DomProcessor {
         this.adapter.setAttr(el, 'autocomplete', 'off');
     }
 
+    // NOTE: We just remove the 'integrity' attribute, because its value is not relevant after the script content
```
Comment (inikulin) [inline src/processing/dom/index.js]: Please, check comment with @VasilyStrelyaev

**Comment by inikulin** [comment]
lgtm, just need to check comment

File: src/processing/dom/index.js [hunk 2]
```diff
@@ -209,6 +216,13 @@ export default class DomProcessor {
...
+    // is changed (http://www.w3.org/TR/SRI/). If this causes problems in the future, we will need to generate
+    // the correct SHA for the changed script.
```
Comment (VasilyStrelyaev) [inline src/processing/dom/index.js]: already checked, but there's nothing that can't be improved
```
    // NOTE: We simply remove the 'integrity' attribute because its value will not be relevant after the script content
    // changes (http://www.w3.org/TR/SRI/). If this causes problems in the future, we will need to generate
    // the correct SHA for the changed script.
```

**Comment by VasilyStrelyaev** [comment]
lgtm

**Comment by churkin** [comment]
FPR

**Comment by inikulin** [comment]
lgtm

**Comment by LavrovArtem** [comment]
lgtm
