### PR TITLE
FIle uploading doesn't work (close #195)

### LINKED ISSUE #195: FIle uploading doesn't work
Reproduced in playground.
You can check it on the [ASPxUploadControl demo page](https://demos.devexpress.com/ASPxFileManagerAndUploadDemos/UploadControl/MultiFileSelection.aspx). Just try to upload any file with hammerhead playground.

### PR DESCRIPTION
**Pull request by churkin**
Content length should be recalculated after upload info injecting.

\сс @inikulin @AlexanderMoskovkin

### CODE REVIEW

File: src/request-pipeline/index.js [hunk 1]
```diff
@@ -90,6 +90,11 @@ var stages = {
 function createReqOpts (ctx) {
     var bodyWithUploads = injectUpload(ctx.req.headers['content-type'], ctx.reqBody);
 
+    if (bodyWithUploads)
```
Comment (inikulin) [inline src/request-pipeline/index.js]: We need comment here about length recalculation. Because, initially it was done this way, but then removed, because it's not clear from code why we can't do it inline

**Comment by inikulin** [comment]
\r-

**Comment by churkin** [comment]
FPR

**Comment by inikulin** [comment]
@churkin Just figured out what we need a regression test for this.
\r-

**Comment by churkin** [comment]
FPR

File: test/server/proxy-test.js [hunk 2]
```diff
@@ -604,5 +608,25 @@ describe('Proxy', function () {
...
+                method:  'POST',
+                body:    src,
+                headers: {
+                    'content-type': 'multipart/form-data; boundary=separator',
+                    'accept':       'text/html,application/xhtml+xml,application/xml;q=0.9,*!/!*;q=0.8'
+                }
+            };
+
+            request(options, function (err, res, body) {
+                expect(body.indexOf('%content-length:' + expected.length + '%')).gt(-1);
```
Comment (inikulin) [inline test/server/proxy-test.js]: Why not strict equality here?

Comment (inikulin) [inline test/server/proxy-test.js]: Or even better we can send back modified body, and compare it to the `expected`.

File: test/server/utils/new-line-replacer.js [hunk 3]
```diff
@@ -0,0 +1,3 @@
+exports.replace = function (content) {
```
Comment (inikulin) [inline test/server/utils/new-line-replacer.js]: Why not call it `replaceNewLines` and just export the whole function?:
```js
module.exports = function(content) {
    return new Buffer(content.toString().replace(/\r\n|\n/gm, '\r\n'));
};
```

Comment (inikulin) [inline test/server/utils/new-line-replacer.js]: Looking at this now, it shouldn't be even named `replaceNewLines` it's too generic for this function, because:
 - it works with buffers only
 - it replaces with '\r\n`
Both are specific for formdata, so it should be called `normalizeFormDataNewLines`

Comment (inikulin) [inline test/server/utils/new-line-replacer.js]: But the best thing will be to not extract utilities at all, just keep this short functions in both files.

**Comment by inikulin** [comment]
\r-

**Comment by churkin** [comment]
FPR

File: test/server/utils/new-line-replacer.js [hunk 4]
```diff
@@ -0,0 +1,3 @@
+module.exports = function replaceNewLines (content) {
```
Comment (inikulin) [inline test/server/utils/new-line-replacer.js]: As I stated previously let's not make utils for this single method, Just keep it inside tests. It's naming is still misleading, because it's very specific to the tests and form data.

**Comment by inikulin** [comment]
\r-

File: src/request-pipeline/index.js [hunk 5]
```diff
@@ -90,6 +90,13 @@ var stages = {
 function createReqOpts (ctx) {
     var bodyWithUploads = injectUpload(ctx.req.headers['content-type'], ctx.reqBody);
 
+    // NOTE: First, we should rewrite the request body, because the 'content-length' header will be built based on it.
+    if (bodyWithUploads)
```
Comment (inikulin) [inline src/request-pipeline/index.js]: \cc @VasilyStrelyaev check comment text, pls

Comment (churkin) [inline src/request-pipeline/index.js]: checked

File: test/server/proxy-test.js [hunk 6]
```diff
@@ -604,5 +611,25 @@ describe('Proxy', function () {
...
+                method:  'POST',
+                body:    src,
+                headers: {
+                    'content-type': 'multipart/form-data; boundary=separator',
+                    'accept':       'text/plain;q=0.9,*!/!*;q=0.8'
+                }
+            };
+
+            request(options, function (err, res, body) {
+                expect(body).eql(expected.length.toString());
```
Comment (inikulin) [inline test/server/proxy-test.js]: Once again: why not send back the body and compare it with `expected`? Why we compare just length and not content?

**Comment by inikulin** [comment]
@churkin Tests failed due to ES6 syntax in tests

**Comment by churkin** [comment]
FPR

**Comment by inikulin** [comment]
lgtm

**Comment by AlexanderMoskovkin** [comment]
lgtm
