### PR TITLE
Hammerhead should remove service data from local storage on the first session page load (close #100)

### LINKED ISSUE #100: Hammerhead should remove service data from local storage on the first session page load
The client `Transport` module saves failed service messages to the localStorage and resend them on the next page load. The localStorage key is the session ID.
We have a problem with the following situation:
1) Start the app and create a hammerhead `Session` (with `id` = 1)
2) Some service message was stored
3) The application process was finished (the next page load did not occur)
4) Start a new application and create a new hammerhead `Session` (it have the same `id` = 1)
5) As a result on the first page load `Transport` get the stored service messages by the `Session` id and  resend them.
I suppose, hammerhead should clear all previous service data from local storage on the first session page load

/cc @churkin @inikulin

### PR DESCRIPTION
**Pull request by churkin**
\cc @AlexanderMoskovkin @inikulin @LavrovArtem

### CODE REVIEW

File: src/client/index.js [hunk 1]
```diff
@@ -92,6 +92,10 @@ class Hammerhead {
         }
     }
 
+    _resetServiceData (sessionId, window) {
```
Comment (inikulin) [inline src/client/index.js]: Method sould be `static` `_resetServiceData`->`cleanLocalStorageServiceData`

File: src/client/task.js.mustache [hunk 2]
```diff
@@ -2,6 +2,7 @@ window.Hammerhead.start({
     cookie                   : '{{{cookie}}}',
     sessionId                : '{{{sessionId}}}',
     serviceMsgUrl            : '{{{serviceMsgUrl}}}',
+    needToResetServiceData   : {{{needToResetServiceData}}},
```
Comment (inikulin) [inline src/client/task.js.mustache]: `needToResetServiceData` -> `isFirstPageLoad`

File: src/session.js [hunk 3]
```diff
@@ -17,10 +17,11 @@ export default class Session extends EventEmitter {
...
         this.uploadStorage = new UploadStorage(uploadStoragePath);
 
-        this.id         = Session._generateSessionId();
-        this.cookies    = new Cookies();
-        this.proxy      = null;
-        this.injectable = {
+        this.id               = Session._generateSessionId();
+        this.cookies          = new Cookies();
+        this.proxy            = null;
+        this.firstPageRequest = true;
```
Comment (inikulin) [inline src/session.js]: You can call it `pageLoadCount`

Comment (inikulin) [inline src/session.js]: And make it a number

File: src/session.js [hunk 4]
```diff
@@ -40,20 +41,24 @@ export default class Session extends EventEmitter {
     }
 
     getTaskScript (referer, cookieUrl, serverInfo, isIFrame, withPayload) {
-        var cookies       = this.cookies.getClientString(cookieUrl);
-        var payloadScript = '';
+        var cookies          = this.cookies.getClientString(cookieUrl);
+        var firstPageRequest = this.firstPageRequest;
+        var payloadScript    = '';
+
+        this.firstPageRequest = false;
```
Comment (inikulin) [inline src/session.js]: Just increment `pageLoadCount` here

File: src/session.js [hunk 5]
```diff
@@ -40,20 +41,24 @@ export default class Session extends EventEmitter {
...
-            cookie:               cookies.replace(/'/g, "\\'"),
-            sessionId:            this.id,
-            serviceMsgUrl:        serverInfo.domain + '/messaging',
-            ie9FileReaderShimUrl: serverInfo.domain + '/ie9-file-reader-shim',
-            crossDomainPort:      serverInfo.crossDomainPort,
-            payloadScript:        payloadScript,
-            referer:              referer
+            cookie:                 cookies.replace(/'/g, "\\'"),
+            sessionId:              this.id,
+            needToResetServiceData: firstPageRequest,
```
Comment (inikulin) [inline src/session.js]: And here you will get:
```js
isFirstPageLoad: this.pageLoadCount === 0
```

File: test/client/fixtures/transport-test.js [hunk 6]
```diff
@@ -11,7 +11,8 @@ var requestIsAsync = false;
 Settings.get().serviceMsgUrl = '/service-msg/100';
 
 function reqisterAfterAjaxSendHook (callback) {
-    callback = callback || function () {};
+    callback = callback || function () {
+        };
```
Comment (inikulin) [inline test/client/fixtures/transport-test.js]: Formatting broken here

**Comment by inikulin** [comment]
\r-

**Comment by churkin** [comment]
FPR

File: test/client/fixtures/transport-test.js [hunk 7]
```diff
@@ -81,7 +81,7 @@ asyncTest('queuedAsyncServiceMsg', function () {
             var expectedCompleteMsgReqs = [10, 500, 200, 300, 200];
 
             deepEqual(completeMsgReqs, expectedCompleteMsgReqs);
-            Transport.asyncServiceMsg = savedAsyncServiceMsgFunc;
+            Transport.asyncServiceMsg   = savedAsyncServiceMsgFunc;
```
Comment (inikulin) [inline test/client/fixtures/transport-test.js]: Unnecessary extra space. Seems like it's formatting bug. Just add a newline to avoid it (actually it's always better to separate assertions from the other code blocks as well as variable assignments)

File: src/session.js [hunk 8]
```diff
@@ -49,6 +50,7 @@ export default class Session extends EventEmitter {
         return mustache.render(TASK_TEMPLATE, {
             cookie:               cookies.replace(/'/g, "\\'"),
             sessionId:            this.id,
+            isFirstPageLoad:      this.pageLoadCount++ === 0,
```
Comment (inikulin) [inline src/session.js]: Avoid using unary operators which modify state within binary expressions (I wonder if we have eslint rule for this). So it should be:
```js
this.pageLoadCount++;
...
isFirstPageLoad: this.pageLoadCount === 1
``` 
Actually, it's my bad, AFAIR it was my suggestion to use comparison with 0. This variant looks semantically correct.

**Comment by inikulin** [comment]
\r-

**Comment by churkin** [comment]
FPR

File: src/session.js [hunk 9]
```diff
@@ -46,15 +47,20 @@ export default class Session extends EventEmitter {
...
             sessionId:            this.id,
+            isFirstPageLoad:      this.pageLoadCount === 0,
             serviceMsgUrl:        serverInfo.domain + '/messaging',
             ie9FileReaderShimUrl: serverInfo.domain + '/ie9-file-reader-shim',
             crossDomainPort:      serverInfo.crossDomainPort,
             payloadScript:        payloadScript,
             referer:              referer
         });
+
+        this.pageLoadCount++;
```
Comment (inikulin) [inline src/session.js]: This is the completely opposite to what I've suggested in previous comment: at the first increment `this.pageLoadCount`, then compare it with `1` not zero.

Comment (inikulin) [inline src/session.js]: It semantically correct and help avoid introducing additional `taskScript` var

**Comment by inikulin** [comment]
\r-

File: src/session.js (hunk 9 above)
Comment (AlexanderMoskovkin) [inline src/session.js]: As for me, the `isFirstPageLoad` variable means that there were no page loads in this session, and the `this.pageLoadCount === 0` check is ok for me

Comment (inikulin) [inline src/session.js]: ok then, let's keep it as is

**Comment by inikulin** [comment]
lgtm

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Comment by LavrovArtem** [comment]
lgtm
