### PR TITLE
Focus-blur sandbox QUnit test doesn't work in Safari (close #171)

### LINKED ISSUE #171: Focus-blur sandbox QUnit test doesn't work in Safari
I've found a `hammerhead`-related qunit test in the `testcafe-phoenix` repo and it fails in Safari now.
We should move it to the `testcafe-hammerhead` and fix it.

The test title contains the 'on recording' string, but the problem was not related to `recorder` but to `hammerhead`.

```js
asyncTest('B237723 - Error on http://phonejs.devexpress.com/Demos/?url=KitchenSink&sm=3 on recording', function () {
    runAsyncTest(
        function () {
            var iframeSrc = window.QUnitGlobals.getResourceUrl('../../../data/focus-blur-sandbox/iframe.html');
            var $iframe   = $('<iframe></iframe>')
                .addClass(TEST_ELEMENT_CLASS)
                .attr('src', iframeSrc)
                .appendTo('body');

            var errorRaised = false;

            $iframe.load(function () {
                try {
                    $iframe[0].contentWindow.focusInput();
                }
                catch (err) {
                    errorRaised = true;
                }

                ok(!errorRaised, 'error is not raised');
                startNext();
            });
        }, 2000);
});
```

//data/focus-blur-sandbox/iframe.html
```html
<!DOCTYPE html>
<html>
<head>
    <title></title>
    <meta charset="utf-8">
    <script src="/hammerhead.js" class="script-hammerhead-shadow-ui"></script>
</head>
<body>
<script type="text/javascript">
    Hammerhead.get('./utils/url').OriginLocation.get = function () {
        return 'http://origin_iframe_host';
    };

    Hammerhead.start({
        crossDomainProxyPort: 2000
    });

    window.focusInput = function () {
        document.getElementById('input').focus();
    };
</script>

<input id="input"/>
</body>
</html>

```

The `ok(!errorRaised, 'error is not raised');` assertion is success but the test failed with the `TypeError: undefined is not an object (evaluating 'Object.prototype)`. It seems the test fails when `MessageSandbox` try to send a message to the top window from the removed iframe

### PR DESCRIPTION
**Pull request by churkin**
\сс @inikulin @LavrovArtem

### CODE REVIEW

**Comment by inikulin** [comment]
requires rebase now

**Comment by churkin** [comment]
Ready to review

File: src/client/sandbox/event/message.js [hunk 1]
```diff
@@ -169,12 +169,16 @@ export default class MessageSandbox extends SandboxBase {
         if (!this._isIFrameRemoved() && (isIFrameWithoutSrc || !isCrossDomainWindows(targetWindow, this.window) &&
                                                                targetWindow[this.RECEIVE_MSG_FN])) {
             //NOTE: postMessage delay imitation
-            nativeMethods.setTimeout.call(this.topWindow, () =>
+            nativeMethods.setTimeout.call(this.topWindow, () => {
+                // NOTE: GH-171
+                if (!isSafari || this.window.top) {
```
Comment (inikulin) [inline src/client/sandbox/event/message.js]: This is cryptic. It took a while for me to decifer, what we shouldn't send message if we missing `window.top` in Safari. I suggest the following:
```js
// NOTE: add comment here about situation when it may happen with GH-issue reference
var isDetachedWindow = isSafari && !this.window.top;

if (!detachedWindow)
```
BTW, should we check for Safari here? We haven't encountered it in other browsers, but wouldn't it be better to use feature detection instead of browser check here (in case it will appear in other browser)?

**Comment by inikulin** [comment]
\r-

File: src/client/sandbox/event/message.js (hunk 1 above)
Comment (churkin) [inline src/client/sandbox/event/message.js]: We want to leave the opportunity to communicate with a removed frame. This may be necessary in some cases. Unfortunately, we can not implement it in the Safari.

**Comment by churkin** [comment]
FPR

File: src/client/sandbox/event/message.js [hunk 2]
```diff
@@ -172,12 +172,19 @@ export default class MessageSandbox extends SandboxBase {
         if (!this._isIframeRemoved() && (isIframeWithoutSrc || !isCrossDomainWindows(targetWindow, this.window) &&
                                                                targetWindow[this.RECEIVE_MSG_FN])) {
             //NOTE: postMessage delay imitation
-            nativeMethods.setTimeout.call(this.topWindow, () =>
+            nativeMethods.setTimeout.call(this.topWindow, () => {
+                // NOTE: We leave the capability to communicate with a removed frame. Unfortunately, this
+                // cannot be done in Safari, because it restricts operations with removed windows (GH-171).
+                var isIframeRemoved = !this.window.top;
+
+                if (!isSafari || !isIframeRemoved) {
```
Comment (inikulin) [inline src/client/sandbox/event/message.js]: Why we need this complicated condition once again?

File: src/client/sandbox/event/message.js [hunk 3]
```diff
@@ -172,12 +172,19 @@ export default class MessageSandbox extends SandboxBase {
         if (!this._isIframeRemoved() && (isIframeWithoutSrc || !isCrossDomainWindows(targetWindow, this.window) &&
                                                                targetWindow[this.RECEIVE_MSG_FN])) {
             //NOTE: postMessage delay imitation
-            nativeMethods.setTimeout.call(this.topWindow, () =>
+            nativeMethods.setTimeout.call(this.topWindow, () => {
+                // NOTE: We leave the capability to communicate with a removed frame. Unfortunately, this
+                // cannot be done in Safari, because it restricts operations with removed windows (GH-171).
+                var isIframeRemoved = !this.window.top;
```
Comment (inikulin) [inline src/client/sandbox/event/message.js]: It's should be `isRemovedIframe`. Anyway, `removed` is not the best word here, `detached` is better.

File: src/client/sandbox/event/message.js (hunk 2 above)
Comment (inikulin) [inline src/client/sandbox/event/message.js]: Why not 
```js
var isUnreachableIframe = isSafari && !this.window.top;
```

File: src/client/sandbox/event/message.js (hunk 3 above)
Comment (inikulin) [inline src/client/sandbox/event/message.js]: Moreover, `removed` iframe is already used here: https://github.com/churkin/testcafe-hammerhead/blob/i171/src/client/sandbox/event/message.js#L104

But it has quite different meaning. And still think we should get rid of Safari check. Seems like removed and reachable iframe will still have `window.top`

**Comment by inikulin** [comment]
\r-

File: src/client/sandbox/event/message.js (hunk 2 above)
Comment (churkin) [inline src/client/sandbox/event/message.js]: I singled the '!this.window.top' expression because i think it can be unclear

Comment (inikulin) [inline src/client/sandbox/event/message.js]: Actually it's much cleaner, because iframe is unreachable only in Safari (as you said), so it makes sense to include it in condition. Because instead I will wonder why we have additional condition for Safari and what does it mean. With this condition I will see what iframes can be unreachable in Safari browser.

**Comment by churkin** [comment]
FPR

**Comment by inikulin** [comment]
lgtm

**Comment by LavrovArtem** [comment]
lgtm
